package bingo.excel.model;

/**
 * Generated by Mr.Robot(Author:crazy_rain) ReadMe: ChangeLog:
 */
public class ExcelImportLog implements java.io.Serializable {

	/**
	 * UID
	 */
	private static final long serialVersionUID = -9044829425429956969L;

	/**
	 * 队列数据的id号
	 */
	private String pid;

	/**
	 * 导入数据所属业务标识
	 */
	private String businessType;

	/**
	 * 文件的上传时间
	 */
	private java.util.Date uploadTime;

	/**
	 * 上传时的文件名
	 */
	private String fileShortName;

	/**
	 * ATTACHMENT 表主键
	 */
	private String attachmentId;

	/**
	 * 文件保存路径（服务器端路径加文件名）
	 */
	private String srcFileSavePath;

	/**
	 * 结果文件保存路径（路径加文件名）
	 */
	private String resultFilePath;

	/**
	 * 开始处理时间
	 */
	private java.util.Date dealBeginTime;

	/**
	 * 结束处理时间
	 */
	private java.util.Date dealEndTime;

	/**
	 * 总记录数
	 */
	private Long totalNums;

	/**
	 * 成功记录数
	 */
	private Long successNums;
	
	/**
	 * 失败记录数
	 */
	private Long errorNums;
	
	/**
	 * 校验通过记录数
	 */
	private Long validatePassNums;

	/**
	 * 当前处理记录行数
	 */
	private Long dealingNum;

	/**
	 * 导入人登录帐号
	 */
	private String importLoginId;

	/**
	 * 处理状态：初始、校验中（1/2步骤）、处理中（2/2步骤）、已处理
	 * 状态变更：初始化中、数据校验中、数据导入中、已处理
	 */
	private String operateStatus;

	/**
	 * 处理结果信息（可用来保存错误信息等）
	 */
	private String operateResultInfo;

	/**
	 * 创建人ID
	 */
	private String createdBy;

	/**
	 * 最后修改人ID
	 */
	private String lastUpdatedBy;

	/**
	 * 创建时间
	 */
	private java.util.Date createdDate;

	/**
	 * 最后修改时间
	 */
	private java.util.Date lastUpdatedDate;
	/**
	 * 导入数据的统计时间
	 */
	private java.util.Date endTime;
	
	

	/**
	 * @return the endTime
	 */
	public java.util.Date getEndTime() {
		return endTime;
	}

	/**
	 * @param endTime the endTime to set
	 */
	public void setEndTime(java.util.Date endTime) {
		this.endTime = endTime;
	}


	/**
	 * @return the pid
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * @param pid the pid to set
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public java.util.Date getUploadTime() {
		return uploadTime;
	}

	public void setUploadTime(java.util.Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getFileShortName() {
		return fileShortName;
	}

	public void setFileShortName(String fileShortName) {
		this.fileShortName = fileShortName;
	}

	public String getAttachmentId() {
		return attachmentId;
	}

	public void setAttachmentId(String attachmentId) {
		this.attachmentId = attachmentId;
	}

	public String getSrcFileSavePath() {
		return srcFileSavePath;
	}

	public void setSrcFileSavePath(String srcFileSavePath) {
		this.srcFileSavePath = srcFileSavePath;
	}

	public String getResultFilePath() {
		return resultFilePath;
	}

	public void setResultFilePath(String resultFilePath) {
		this.resultFilePath = resultFilePath;
	}

	public java.util.Date getDealBeginTime() {
		return dealBeginTime;
	}

	public void setDealBeginTime(java.util.Date dealBeginTime) {
		this.dealBeginTime = dealBeginTime;
	}

	public java.util.Date getDealEndTime() {
		return dealEndTime;
	}

	public void setDealEndTime(java.util.Date dealEndTime) {
		this.dealEndTime = dealEndTime;
	}

	public Long getTotalNums() {
		return totalNums;
	}

	public void setTotalNums(Long totalNums) {
		this.totalNums = totalNums;
	}

	public Long getSuccessNums() {
		return successNums;
	}

	public void setSuccessNums(Long successNums) {
		this.successNums = successNums;
	}

	public Long getErrorNums() {
		return errorNums;
	}

	public void setErrorNums(Long errorNums) {
		this.errorNums = errorNums;
	}

	public Long getValidatePassNums() {
		return validatePassNums;
	}

	public void setValidatePassNums(Long validatePassNums) {
		this.validatePassNums = validatePassNums;
	}

	public Long getDealingNum() {
		return dealingNum;
	}

	public void setDealingNum(Long dealingNum) {
		this.dealingNum = dealingNum;
	}

	public String getImportLoginId() {
		return importLoginId;
	}

	public void setImportLoginId(String importLoginId) {
		this.importLoginId = importLoginId;
	}

	public String getOperateStatus() {
		return operateStatus;
	}

	public void setOperateStatus(String operateStatus) {
		this.operateStatus = operateStatus;
	}

	public void setOperateResultInfo(String operateResultInfo) {
		this.operateResultInfo = operateResultInfo;
	}

	public String getOperateResultInfo() {
		return operateResultInfo;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public java.util.Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}

	public java.util.Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}
}