
package net.bioslink.manage.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ImsImgInfoService", targetNamespace = "http://webservice.manage.bioslink.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImsImgInfoService {


    /**
     * 
     * @param cardNo
     * @param project
     * @param unit
     * @param archDate
     * @param docType
     * @param docSubType
     * @param custName
     * @param custPaperNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "cardImgInfoResult", targetNamespace = "")
    @RequestWrapper(localName = "queryCardImgInfo", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.QueryCardImgInfo")
    @ResponseWrapper(localName = "queryCardImgInfoResponse", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.QueryCardImgInfoResponse")
    public String queryCardImgInfo(
        @WebParam(name = "unit", targetNamespace = "")
        String unit,
        @WebParam(name = "project", targetNamespace = "")
        String project,
        @WebParam(name = "docType", targetNamespace = "")
        String docType,
        @WebParam(name = "docSubType", targetNamespace = "")
        String docSubType,
        @WebParam(name = "cardNo", targetNamespace = "")
        String cardNo,
        @WebParam(name = "custName", targetNamespace = "")
        String custName,
        @WebParam(name = "custPaperNo", targetNamespace = "")
        String custPaperNo,
        @WebParam(name = "archDate", targetNamespace = "")
        String archDate);

    /**
     * 
     * @param project
     * @param unit
     * @param archDate
     * @param docType
     * @param pageNo
     * @param pageSize
     * @param docSubType
     * @param code
     * @return
     *     returns java.util.List<net.bioslink.manage.webservice.ImsImgInfoVO>
     */
    @WebMethod
    @WebResult(name = "imgInfoPageResult", targetNamespace = "")
    @RequestWrapper(localName = "queryImgInfoByPage", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.QueryImgInfoByPage")
    @ResponseWrapper(localName = "queryImgInfoByPageResponse", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.QueryImgInfoByPageResponse")
    public List<ImsImgInfoVO> queryImgInfoByPage(
        @WebParam(name = "unit", targetNamespace = "")
        String unit,
        @WebParam(name = "project", targetNamespace = "")
        String project,
        @WebParam(name = "code", targetNamespace = "")
        String code,
        @WebParam(name = "docType", targetNamespace = "")
        String docType,
        @WebParam(name = "docSubType", targetNamespace = "")
        String docSubType,
        @WebParam(name = "archDate", targetNamespace = "")
        String archDate,
        @WebParam(name = "pageNo", targetNamespace = "")
        int pageNo,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize);

    /**
     * 
     * @param fileCode
     * @param custCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "writeResult", targetNamespace = "")
    @RequestWrapper(localName = "writeBackCustCode", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.WriteBackCustCode")
    @ResponseWrapper(localName = "writeBackCustCodeResponse", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.WriteBackCustCodeResponse")
    public String writeBackCustCode(
        @WebParam(name = "fileCode", targetNamespace = "")
        String fileCode,
        @WebParam(name = "custCode", targetNamespace = "")
        String custCode);

    /**
     * 
     * @param project
     * @param unit
     * @param docType
     * @param year
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getFileCode", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.GetFileCode")
    @ResponseWrapper(localName = "getFileCodeResponse", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.GetFileCodeResponse")
    public String getFileCode(
        @WebParam(name = "unit", targetNamespace = "")
        String unit,
        @WebParam(name = "project", targetNamespace = "")
        String project,
        @WebParam(name = "docType", targetNamespace = "")
        String docType,
        @WebParam(name = "year", targetNamespace = "")
        int year);

    /**
     * 
     * @param project
     * @param unit
     * @param archDate
     * @param count
     * @param docType
     * @param custCode
     * @param docSubType
     * @param code
     * @param houseCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "imgInfoResult", targetNamespace = "")
    @RequestWrapper(localName = "queryImgInfo", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.QueryImgInfo")
    @ResponseWrapper(localName = "queryImgInfoResponse", targetNamespace = "http://webservice.manage.bioslink.net/", className = "net.bioslink.manage.webservice.QueryImgInfoResponse")
    public String queryImgInfo(
        @WebParam(name = "unit", targetNamespace = "")
        String unit,
        @WebParam(name = "project", targetNamespace = "")
        String project,
        @WebParam(name = "custCode", targetNamespace = "")
        String custCode,
        @WebParam(name = "houseCode", targetNamespace = "")
        String houseCode,
        @WebParam(name = "code", targetNamespace = "")
        String code,
        @WebParam(name = "docType", targetNamespace = "")
        String docType,
        @WebParam(name = "docSubType", targetNamespace = "")
        String docSubType,
        @WebParam(name = "archDate", targetNamespace = "")
        String archDate,
        @WebParam(name = "count", targetNamespace = "")
        int count);

}
